version: '3.8'

networks:
  evilcorp_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.99.0.0/16

services:
  nginx-proxy:
    image: nginx:latest
    container_name: evilcorp-router
    networks:
      evilcorp_net:
        aliases:
          - bootcamp.local
          - lab1.evilcorp.local
          - lab3.evilcorp.local
        ipv4_address: 172.99.0.5
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

  bootcamp-portal:
    build:
      context: ./portal
      dockerfile: Dockerfile
    container_name: bootcamp-portal
    networks:
      evilcorp_net:
        ipv4_address: 172.99.0.3
    restart: unless-stopped

  lab1-recon-target:
    build:
      context: ./labs/lab-1-recon
      dockerfile: Dockerfile
    container_name: lab1-recon-box
    networks:
      evilcorp_net:
        ipv4_address: 172.99.0.4
    restart: unless-stopped

  lab3-injection-target:
    build:
      context: ./labs/lab-3-injection
      dockerfile: Dockerfile
    container_name: lab3-injection-box
    networks:
      evilcorp_net:
        aliases:
          - lab3.evilcorp.local
        ipv4_address: 172.99.0.6
    ports:
      - "2223:22"   # Optional: expose SSH for manual testing if needed
    restart: unless-stopped

  attacker-box:
    image: custom-kali-attacker:latest
    container_name: attacker-box
    build:
      context: ./attacker-box
      dockerfile: Dockerfile
    networks:
      evilcorp_net:
        ipv4_address: 172.99.0.2
    stdin_open: true
    tty: true
    restart: unless-stopped
