version: '3.8'

networks:
  evilcorp_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.99.0.0/16  # Changed to a fresh subnet

services:
  nginx-proxy:
    image: nginx:latest
    container_name: evilcorp-router
    networks:
      - evilcorp_net
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

  bootcamp-portal:
    build:
      context: ./portal
      dockerfile: Dockerfile
    container_name: bootcamp-portal
    networks:
      - evilcorp_net
    restart: unless-stopped

  lab1-recon-target:
    build:
      context: ./labs/lab-1-recon
      dockerfile: dockerfile
    container_name: lab1-recon-box
    networks:
      - evilcorp_net
    restart: unless-stopped

  attacker-box:
    image: kalilinux/kali-rolling
    container_name: attacker-box
    networks:
      - evilcorp_net
    stdin_open: true
    tty: true
    restart: unless-stopped