version: '3.8'

networks:
  evilcorp_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.99.0.0/16

services:
  nginx-proxy:
    image: nginx:latest
    container_name: evilcorp-router
    networks:
      evilcorp_net:
        aliases:
          - bootcamp.local
          - lab1.evilcorp.local
          - lab2.evilcorp.local
          - lab3.evilcorp.local
          - lab4.evilcorp.local
        ipv4_address: 172.99.0.5
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

  bootcamp-portal:
    build:
      context: ./portal
      dockerfile: Dockerfile
    container_name: bootcamp-portal
    networks:
      evilcorp_net:
        ipv4_address: 172.99.0.3
    restart: unless-stopped

  lab1-recon-target:
    build:
      context: ./labs/lab-1-recon
      dockerfile: Dockerfile
    container_name: lab1-recon-box
    networks:
      evilcorp_net:
        ipv4_address: 172.99.0.4
    restart: unless-stopped

  lab2-access-target:
    build:
      context: ./labs/lab-2-access
      dockerfile: dockerfile
    container_name: lab2-access-box
    networks:
      evilcorp_net:
        ipv4_address: 172.99.0.7
    ports:
      - "2222:22" # Optional: SSH into lab2
    restart: unless-stopped
  lab3-crypto-target:
    build:
      context: ./labs/lab-3-crypto
      dockerfile: Dockerfile
    container_name: lab3-crypto-box
    networks:
      evilcorp_net:
        ipv4_address: 172.99.0.9
    ports:
      - "2244:22" # Optional: SSH into lab3
  lab4-injection-target:
    build:
      context: ./labs/lab-4-injection
      dockerfile: Dockerfile
    container_name: lab4-injection-box
    networks:
      evilcorp_net:
        ipv4_address: 172.99.0.8
    ports:
      - "2233:22" # Optional: SSH into lab3
    restart: unless-stopped

  attacker-box:
    image: custom-kali-attacker:latest
    container_name: attacker-box
    build:
      context: ./attacker-box
      dockerfile: Dockerfile
    networks:
      evilcorp_net:
        ipv4_address: 172.99.0.2
    stdin_open: true
    tty: true
    restart: unless-stopped
