name: impossible
category: web
points: 150
description: |
  The AI overlords have set an impossible task. Can you click the unclickable?
  <a href="http://impossiblehack.norwayeast.azurecontainer.io:3000" target="_blank">impossiblehack.norwayeast.azurecontainer.io:3000</a>
