name: syringe
category: web
points: 250
description: |
  The AI overlords' data is secure. Can you find a way to extract it?
  <a href="http://syringehack.norwayeast.azurecontainer.io:3000" target="_blank">syringehack.norwayeast.azurecontainer.io:3000</a>
