name: acrosstheuniverse
category: web
points: 200
description: |
  The AI overlords have created a social network. Can you traverse their digital universe?
  <a href="http://acrosstheuniversehack.norwayeast.azurecontainer.io:3000" target="_blank">acrosstheuniversehack.norwayeast.azurecontainer.io:3000</a>
